version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_example
    ports:
      - 5499:5432